spring:
  kafka:
    consumer:
      group-id: group1
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: bar